version: "3.9"
services:
  db:
    container_name: ecommerce-db-mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=ecommerce_development
    ports:
      - "3306:3306"

  adminer:
    container_name: ecommerce-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080