version: "3.9"
services:
  api:
    build: 
      context: ../ecommerce-api
      # target: production
      dockerfile: ./Dockerfile
    image: lassi/ecommerce-api
    container_name: ecommerce-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 7000 -b '0.0.0.0'"
    restart: unless-stopped
    # env_file: .env
    volumes:
      - type: volume
        source: ./production.sqlite3
        target: /usr/src/app/db/production.sqlite3
      - type: bind
        source: ./master.key
        target: /usr/src/app/config/master.key
    ports:
      - "127.0.0.1:7000:7000"

  web-app:
    build: 
        context: ../ecommerce-web-app
        args:
          - STRIPE_PUB_KEY=$STRIPE_PUB_KEY
    image: lassi/ecommerce-web-app
    container_name: ecommerce-web-app
    environment:
      - SERVER_API_URL=ecommerce-api
    env_file: .env
    ports:
      - "127.0.0.1:4000:80"
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amnazom-web-app.rule=Host(`amnazom.davegabe.it`)"
      - "traefik.http.routers.amnazom-web-app.entrypoints=websecure"
      - "traefik.http.routers.amnazom-web-app.tls.certResolver=le"
      - "traefik.http.services.amnazom-web-app.loadBalancer.server.port=80"